version: '3'

services:
  app:
    build: .
    volumes:
      - type: bind
        source: ./app/output
        target: /app/output
      - type: bind
        source: ./app/config.yml
        target: /app/config.yml
    # for debug 
    # stdin_open: true
    # tty: true